# Generated by Django 4.1.1 on 2022-11-24 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='имя')),
                ('telephone', models.CharField(max_length=20, verbose_name='телефон')),
                ('delivery_type', models.CharField(max_length=40, verbose_name='имя')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='имя')),
                ('telephone', models.CharField(max_length=20, verbose_name='телефон')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('address', models.CharField(max_length=40, verbose_name='адрес')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrived', models.DateTimeField(verbose_name='дата доставки')),
                ('payment_method', models.CharField(max_length=10)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.courier')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_get', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('courier', models.ManyToManyField(through='delivery.DeliveryList', to='delivery.courier')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrdersProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='кол-во')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='товар')),
                ('description', models.TextField(verbose_name='описание')),
                ('image', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/', verbose_name='фото')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('order', models.ManyToManyField(through='delivery.OrdersProducts', to='delivery.order')),
            ],
        ),
        migrations.AddField(
            model_name='ordersproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.product'),
        ),
        migrations.AddField(
            model_name='deliverylist',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.order'),
        ),
    ]
