# Generated by Django 4.1.1 on 2022-12-18 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_order_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
