# Generated by Django 4.1.1 on 2022-12-18 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_delete_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user',
        ),
    ]
